Metrics/AbcSize:
  Max: 17
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 400
Style/MultilineBlockChain:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
