#!/bin/sh

INFILE="$1"
OUTFILE="`basename -s '.md' "$INFILE"`.pdf"

pandoc -s \
    --pdf-engine=xelatex \
    --variable papersize=a4 \
    --variable documentclass=scrartcl \
    --variable classoption=11pt \
    --variable mainfont="DejaVu Serif" \
    --variable sansfont="DejaVu Sans" \
    --variable monofont="DejaVu Sans Mono" \
    --variable lang=de \
    --variable urlcolor=blue \
    $INFILE -o $OUTFILE
